# Generated by Django 3.2.25 on 2025-02-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shopcollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCollection',
        ),
    ]
