# Generated by Django 3.2.25 on 2025-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomePageSeasonTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('HomePageImage', models.ImageField(upload_to='')),
                ('HomePageImageTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('HomePageParagraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
