# Generated by Django 3.2.25 on 2025-02-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=250, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('Email', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
