# Generated by Django 3.2.25 on 2025-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SalePrice',
            field=models.FloatField(blank=True, default=0, verbose_name='سعر العرض'),
        ),
        migrations.AddField(
            model_name='product',
            name='isOnSale',
            field=models.BooleanField(default=False, verbose_name='المنتج عليه عرض'),
        ),
        migrations.AddField(
            model_name='product',
            name='isSoldOut',
            field=models.BooleanField(default=False, verbose_name='المنتج غير متاح'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(default=False, verbose_name='منتج جديد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
