# Generated by Django 3.2.25 on 2025-03-03 15:21

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderId',
            field=models.CharField(default=store.models.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
    ]
