# Generated by Django 3.2.25 on 2025-03-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_address_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.address'),
        ),
    ]
