# Generated by Django 3.2.25 on 2025-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20250304_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipping', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=15, verbose_name='حالة الطلب'),
        ),
    ]
